repos:
  - repo: https://github.com/oxsecurity/megalinter
    rev: v8.8.0
    hooks:
      - id: megalinter-incremental
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
        args:
          - -x
          - "@commitlint/config-conventional"
        additional_dependencies:
          - "@commitlint/config-conventional"
          - "@commitlint/cli"
