---
# Release workflow
permissions: write-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Test
        run: go test -v ./...
      - name: Compile
        run: go build .

  release:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
      - name: Add dependencies
        run: npm i @commitlint/config-conventional
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deliver:
    permissions:
      packages: write
      id-token: write
      contents: read
    needs:
      - release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pack CLI
        uses: buildpacks/github-actions/setup-pack@v5.9.3
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        env:
          IMAGE_TAG: latest
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pack build "ghcr.io/brucellino/nomad-traefik-cloudflare-controller:${IMAGE_TAG}" \
            --builder "heroku/builder:24" --path=. \
            --env CGO_ENABLED=0 \
            --env BP_OCI_TITLE="Nomad Traefik Cloudflare Controller" \
            --env BP_OCI_DESCRIPTION="Controller for managing Cloudflare DNS records for Traefik ingress in Nomad" \
            --env BP_OCI_URL="https://github.com/brucellino/nomad-traefik-cloudflare-controller" \
            --env BP_OCI_SOURCE="https://github.com/brucellino/nomad-traefik-cloudflare-controller" \
            --env BP_OCI_VERSION="latest" \
            --env BP_OCI_REVISION="latest" \
            --env BP_OCI_VENDOR="brucellino" \
            --env BP_OCI_LICENSES="MIT" \
            --publish
